services:
  server:
    container_name: open-food-today-server
    build:
      context: ./server
      dockerfile: ./entrypoint/Dockerfile
    env_file: "./.env"
    environment:
      HOST: 0.0.0.0
    ports:
      - 3310:3310
    restart: unless-stopped
