// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { "Custom": [string, number] } | { "InternalServer": string } | { "Unauthorized": string } | { "Forbidden": string } | { "Validation": string };

export type ErrorResponse = { error_code: string, message: string, };
