// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecipeLike = { id: number; recipe_id: number; user_id: string; created_at: string };

export type RecipeLikeRequest = { recipe_id: number };

export type UserIdRequest = { user_id: string };

export type UserLikeStats = { user_id: string; user_liked: boolean };
