// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecipeComment = {
	id: number;
	recipe_id: number;
	user_id: string;
	parent_id: number | null;
	reply_to: number | null;
	level: number;
	content: string;
	created_at: string;
	updated_at: string;
};
