// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicRecipe = {
	id: number;
	title: string;
	link: string | null;
	description: string | null;
	author: string | null;
	image_url: string | null;
	created_at: string;
	author_name: string | null;
	author_avatar_url: string | null;
	likes_count: number | null;
	comments_count: number | null;
};

export type Recipe = {
	id: number;
	title: string;
	link: string | null;
	description: string | null;
	author: string | null;
	image_url: string | null;
	created_at: string;
};
