// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Recipe = {
	id: number;
	title: string;
	link: string | null;
	description: string | null;
	author: string | null;
	image_url: string | null;
	created_at: string;
};
