// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Recipe = { id: bigint, title: string, link: string | null, description: string | null, author: bigint | null, image_url: string | null, created_at: string, };
